spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.12.116.58:3306/feiyanai?useUnicode=true&characterEncoding=utf-8
#    url: jdbc:mysql://localhost:3306/feiyanai?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ZhangTianHui2019@
  #    password: "!QAZ2wsx"

#    url: jdbc:mysql://39.108.37.131:3306/feiyanai?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
#    username: root
#    password: root
  jpa:
    show-sql: true
